import { For, Show } from "solid-js";
import type { Workspace } from "../../../api/contracts";
import { emptyEntryCounts, overviewHref, type EntryCounts, type OverviewRow, type OverviewSort, type OverviewState } from "../overview-model";
import { TYPE_COLUMNS } from "./OverviewControls";

export const PAGE_SIZE = 25;
const SORT_HEADING: Record<OverviewSort, string> = { burden: "Files by burden", findings: "Files by finding count", depth: "Files by path depth", file: "Files by path" };
export function OverviewResults(props: { report: Workspace; state: OverviewState; rows: OverviewRow[]; pageRows: OverviewRow[]; typeCounts: Map<string, EntryCounts> }) {
  const totalPages = () => Math.max(1, Math.ceil(props.rows.length / PAGE_SIZE));
  const rangeStart = () => props.rows.length ? (props.state.all ? 1 : (props.state.page - 1) * PAGE_SIZE + 1) : 0;
  const rangeEnd = () => props.state.all ? props.rows.length : Math.min(props.rows.length, props.state.page * PAGE_SIZE);
  return <>
    <SummaryCards summary={props.report.summary} />
    <Show when={props.report.comparison}>{(comparison) => <section class="comparison-summary" aria-label="Baseline comparison"><strong>Compared with baseline</strong><span>{comparison().worsened} worsened</span><span>{comparison().improved} improved</span><span>{comparison().resolved.length} resolved</span><For each={Object.entries(comparison().metricDeltas)}>{([metric, delta]) => <span classList={{ regression: delta > 0, improvement: delta < 0 }}>{metric} {delta > 0 ? `+${delta}` : delta}</span>}</For><Show when={comparison().newTop}>{(finding) => <a href={`/file?path=${encodeURIComponent(finding().path)}#L${finding().line}`}>New top: {finding().label}</a>}</Show></section>}</Show>
    <h2>{SORT_HEADING[props.state.sort]}</h2>
    <Show when={props.report.concentration.fileCount > 0}><p class="meta">Top {Math.min(5, props.report.concentration.fileCount)} file(s) hold {Math.round(props.report.concentration.top5 * 100)}% of ranked burden · {props.report.concentration.fileCount} file(s) with ≥1 finding, {props.report.concentration.hot4Plus} with ≥4.</p></Show>
    <p class="meta">{props.rows.length ? `Showing ${rangeStart()}-${rangeEnd()} of ${props.rows.length} file${props.rows.length === 1 ? "" : "s"}` : "No matching files"}</p>
    <table class="overview-table" id="overview-table"><thead><tr><SortHeader state={props.state} sort="file" label="File" /><SortHeader state={props.state} sort="findings" label="Findings" /><SortHeader state={props.state} sort="burden" label="Worst" /><SortHeader state={props.state} sort="depth" label="Path depth" /><For each={TYPE_COLUMNS}>{(column) => <th class={`col-${column.col} num`}>{column.label}</th>}</For><th>Dominant shape</th><th>Ownership</th><th>First cut</th><Show when={props.report.comparison}><th>Change</th></Show></tr></thead>
      <tbody><Show when={props.pageRows.length} fallback={<tr><td colspan={12} class="meta">No matching files.</td></tr>}><For each={props.pageRows}>{(row) => { const counts = () => props.typeCounts.get(row.key) ?? emptyEntryCounts(); const change = () => props.report.files.find((file) => file.path === row.key)?.comparisonState ?? "unchanged"; return <tr><td><a href={`/file?path=${encodeURIComponent(row.key)}`}>{row.key}</a></td><td>{row.count}</td><td>{row.worst.toFixed(2)}</td><td>{row.depth}</td><For each={TYPE_COLUMNS}>{(column) => <td class={`col-${column.col} num`}>{counts()[column.key] || <span class="meta">·</span>}</td>}</For><td>{row.shape}</td><td>{row.ownership}</td><td>{row.firstCut}</td><Show when={props.report.comparison}><td><span class={`change-state state-${change()}`}>{change()}</span></td></Show></tr>; }}</For></Show></tbody></table>
    <Show when={!props.state.all && totalPages() > 1}><nav class="pager" aria-label="File result pages"><a class="btn" classList={{ disabled: props.state.page <= 1 }} href={overviewHref(props.state, { page: props.state.page - 1 })}>Previous</a><span class="meta">Page {props.state.page} of {totalPages()}</span><a class="btn" classList={{ disabled: props.state.page >= totalPages() }} href={overviewHref(props.state, { page: props.state.page + 1 })}>Next</a><a class="btn" href={overviewHref(props.state, { all: true })}>Show all {props.rows.length}</a></nav></Show>
    <Show when={props.state.all && props.rows.length > PAGE_SIZE}><nav class="pager"><a class="btn" href={overviewHref(props.state, { all: false, page: 1 })}>Paginate</a></nav></Show>
  </>;
}
function SummaryCards(props: { summary: Workspace["summary"] }) { const items = () => [["Sinks", props.summary.sinks], ["Sources", props.summary.sources], ["Path families", props.summary.pathFamilies], ["Unknown edges", props.summary.unknownEdges], ["Graph nodes", props.summary.nodes]] as const; return <div class="cards"><For each={items()}>{([label, value]) => <div class="card"><div class="n">{value}</div><div class="l">{label}</div></div>}</For></div>; }
function SortHeader(props: { state: OverviewState; sort: OverviewSort; label: string }) { const active = () => props.state.sort === props.sort; return <th class="sortable" classList={{ active: active() }} aria-sort={active() ? "descending" : undefined}><a href={overviewHref(props.state, { sort: props.sort, page: 1 })}><span>{props.label}</span><Show when={active()}><span class="caret">▼</span></Show></a></th>; }
