import path from "node:path";

export function commandPath(targetPath) {
  const relative = path.relative(process.cwd(), targetPath);
  if (relative && !relative.startsWith("..") && !path.isAbsolute(relative))
    return relative;
  if (relative === "") return ".";
  return targetPath;
}

export function tableReport(title, headers, rows, intro = []) {
  const lines = [
    `# ${title}`,
    "",
    ...intro,
    ...formatMarkdownTable(headers, rows),
  ];
  return `${lines.join("\n")}\n`;
}

// A short at-a-glance header for every report: where it came from and what the
// view shows / what its terms mean. Reports are often read without the analyzer
// source at hand, so this has to stand alone. Rendered as a blockquote note.
export function viewIntro(view, report) {
  const root = report?.meta?.root ?? null;
  const displayRoot = root ? commandPath(root) : null;
  const generated = report?.generatedAt
    ? report.generatedAt.slice(0, 10)
    : null;
  const provenance =
    `Generated by **tsx-dataflow**, a static render-path data-flow analyzer for ` +
    `TypeScript/TSX (Solid/SolidStart-aware)` +
    (displayRoot ? `, from \`${displayRoot}\`` : "") +
    (generated ? ` on ${generated}` : "") +
    `.`;
  const method =
    `It parses the source and builds a graph from each value (props, signals, ` +
    `hooks, locals) through every transformation to the JSX **sink** that renders ` +
    `it, then ranks the heaviest render paths.`;
  const blurb = VIEW_BLURBS[view] ?? "";
  const lines = [`> ${provenance} ${method}`];
  lines.push(
    ">",
    "> Terminology: _source_/_sink_ name code positions in the static graph; counts, scores, reach, depth, and wrapper steps are analyzer-computed signals, not product accounts or runtime telemetry. A _wrapper step_ is a representation-only hop such as an alias, object pack, or spread; it can signal reviewability burden, but it should be weighed with burden score, defensive operation entries, reach, and pack/relay verdicts before choosing work.",
  );
  if (blurb) lines.push(">", `> ${blurb}`);
  lines.push("");
  return lines;
}

// Per-view "what am I looking at" sentence(s): what the rows are and what the
// non-obvious column/field names mean.
export const VIEW_BLURBS = {
  overview:
    "The orientation document: read this first. It guides you to every other " +
    "report (what each is for) and carries the workspace aggregates — hotspot " +
    "concentration by file, the repair buckets (peripheral quick wins, central " +
    "leverage, investigate), and an unknown-edge diagnostic section — so you have " +
    "one place to make sense of the dump before opening a focused report.",
  findings:
    "Each finding is one render **sink** (a value rendered into the DOM). " +
    "_Sink_ is the rendered expression, _Source_ the actionable inputs it derives " +
    "from, _path depth_ the number of transformation hops between them, and " +
    "_severity/burden_ reflects how much data-flow plumbing sits on the path.",
  "repeated-forks":
    "Each entry is one component that tests the **same discriminant** in two or " +
    "more sibling branch sites (ternary, `if`, `&&`, Solid `<Match>`/`<Show>`) — " +
    "the signal that it wants to split into discriminated sub-components. _Fork " +
    "sites_ are where the condition repeats; _branch-exclusive values_ are " +
    "component-scope derivations computed eagerly but read under only one branch.",
  "work-packets":
    "Each work item is a scoped cleanup candidate for one render sink. _pivot_ is " +
    "the primary source value, _source inputs_ the distinct inputs merged into it " +
    "(fan-in), _reachable sinks_ how many render sites the same sources feed, and " +
    "the representative path lists every transformation hop from source to JSX " +
    "with its operation kind.",
  "fan-out":
    "Ranks source values by how many render sinks consume them. _Sinks_ is that " +
    "consumer count, _Files_ how many files reference the source, _Example sink_ a " +
    "representative file:line to open first, and _Max depth_ the longest " +
    "transformation path from that source to JSX. Prop reads are scoped to their " +
    "owning component (shown as `Component › props.x`) so a common prop name is not " +
    "merged across unrelated components; hooks, imports, and context values stay " +
    "keyed globally since they really are one shared source.",
  "fan-in":
    "Ranks render sinks by how many independent inputs they merge. _Root sources_ " +
    "is the fan-in count, _Predicates_ the number of conditional branches on the " +
    "path, and _Max distance_ the longest transformation path feeding the sink.",
  "path-families":
    "Groups render paths by structural _signature_ (a depth band plus the sequence " +
    "of operation kinds) so recurring shapes surface. _Paths_/_Sinks_ count the " +
    "family's members and _Max depth_ is the deepest path in it.",
  "defensive-ledger":
    "Lists defensive operations (optional chains, nullish fallbacks) on render " +
    "paths. _Verdict_ is whether the guard can ever fire given the TypeScript " +
    "types: _impossible_ means the guarded value is never nullish, so the defense " +
    "is dead code; _possible_ means it can; _unknown_ means the type is too loose " +
    "to tell. _Action_ separates stale guards from fallbacks that establish certainty.",
  "prop-relay":
    "Render sinks that mostly relay data across component boundaries. _Component " +
    "boundaries_ counts prop hand-offs, _Wrapper steps_ counts representation-only repacks, and " +
    "_Classification_ marks whether the relay transforms the data or just passes it " +
    "through.",
  "context-relay":
    "Same-feature components receiving prop bundles from a context-aware parent — " +
    "candidates for moving shared state behind a Provider/Context instead of " +
    "threading props. Lists the parent's context hooks and the props it forwards.",
  "boundary-report":
    "First-party functions reached while tracing render paths, scored as data-flow " +
    "boundaries. _In-src_ = distinct values reaching the return; _Callers_ = call " +
    "sites across analyzed files; _Internal d/churn_ = depth/representation churn " +
    "inside the body. _Verdict_ flags clean pipes, thin pass-throughs (inline), " +
    "leaky boundaries, confluence/junctions, and hidden-mess internals.",
  "component-refs":
    "Where each component is used. The JSX tag is resolved to its declaration by " +
    "symbol (not by name), so a renamed import or a same-named local is counted " +
    "correctly. _Uses_ is the total render count; _Used by_ lists representative " +
    "call sites. (First slice: capitalized component tags; member tags like " +
    "`Foo.Bar` and non-component symbols come later.)",
  junctions:
    "Functions where independent source lineages fork in (_tributaries_) and the " +
    "result re-spreads to multiple call sites (_distributaries_) — the load-bearing " +
    "knots. Ranked by in-sources × callers. These are the highest-leverage targets " +
    "for either formalizing a typed boundary or splitting by consumer.",
  "inline-preview":
    "An inline-vs-keep call for each helper on a render path: how the path shortens " +
    "(or lengthens) if the helper were folded in, plus a verdict. INLINE removes a " +
    "needless hop; KEEP/FORMALIZE means the helper consolidates real work. Proposes, " +
    "never rewrites.",
};

// Render a GitHub-flavored Markdown table with prettier-style column alignment:
// every column is padded to the widest (visible) cell, and the separator row's
// dashes fill the same width. Cells are sanitized via formatTableCell (newlines
// collapsed, pipes escaped); padding is computed on the *visible* width so an
// escaped pipe (`\|`, two source chars, one rendered char) still aligns.
export function formatMarkdownTable(headers, rows) {
  const grid = [headers, ...rows].map((row) =>
    headers.map((_, column) => formatTableCell(row[column] ?? "")),
  );
  const widths = headers.map((_, column) =>
    Math.max(3, ...grid.map((row) => cellWidth(row[column]))),
  );
  const renderRow = (row) =>
    `| ${row.map((cell, column) => padCell(cell, widths[column])).join(" | ")} |`;
  const separator = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
  return [renderRow(grid[0]), separator, ...grid.slice(1).map(renderRow)];
}

function formatTableCell(value) {
  return String(value).replaceAll("\n", " ").replaceAll("|", "\\|");
}

// A small two-column metric/value table. Numeric and label metrics read better
// as an aligned table than as a fenced block; fences are reserved for code.
export function metricTable(pairs) {
  return formatMarkdownTable(
    ["Metric", "Value"],
    pairs.map(([label, value]) => [label, String(value)]),
  );
}

// Visible width of an already-escaped cell. GFM unescapes `\|` to `|` before
// rendering, so each escaped pipe occupies one rendered column, not two.
function cellWidth(escaped) {
  return escaped.length - (escaped.match(/\\\|/g)?.length ?? 0);
}

function padCell(escaped, width) {
  return escaped + " ".repeat(Math.max(0, width - cellWidth(escaped)));
}

// Wrap a code-ish cell value as a Markdown code span so it renders monospaced.
// Safe inside a table cell: GFM strips the table pipe-escaping before inline
// code parsing, so backticks and escaped pipes coexist. Expressions often embed
// backticks (template literals), so the delimiter is a backtick run one longer
// than any internal run, with a pad space when the text starts/ends with a
// backtick (GFM strips one space each side). Empty values are left untouched.
export function code(value) {
  const text = String(value).trim();
  if (!text) return "";
  const longestRun = Math.max(
    0,
    ...(text.match(/`+/g) ?? []).map((run) => run.length),
  );
  const fence = "`".repeat(longestRun + 1);
  const pad = text.startsWith("`") || text.endsWith("`") ? " " : "";
  return `${fence}${pad}${text}${pad}${fence}`;
}

// A fenced code block for the indented (prose) renderers. In GitHub-flavored
// Markdown a 2-space indent does NOT create a code block, so aligned metric
// columns and multi-line expressions collapse into re-wrapped prose. Fencing the
// monospace payload preserves alignment. `content` is one entry per line
// (already one-lined). Backticks are stripped from the payload: everything in
// the block is already monospace, so a template literal's source backticks
// (`` `link-${id}` ``) read as stray markdown ticks rather than signal — and a
// stray "```" line would otherwise close the fence early.
export function fenced(content) {
  return [
    "```",
    ...content.map((line) => String(line).replaceAll("`", "")),
    "```",
  ];
}
